# Generated by Django 5.2.9 on 2025-12-10 04:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('joined_date', models.DateField(null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)])),
                ('email', models.CharField(max_length=255, null=True, unique=True)),
                ('phone', models.IntegerField(null=True, validators=[django.core.validators.MinLengthValidator(10)])),
            ],
        ),
    ]
