# Generated by Django 5.2.9 on 2025-12-15 10:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('member', 'Member'), ('head', 'Head'), ('secretariat', 'Secretariat'), ('admin', 'Admin')], max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits')]),
        ),
        migrations.AddField(
            model_name='member',
            name='departments',
            field=models.ManyToManyField(blank=True, to='members.department'),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.role'),
        ),
    ]
