# Generated by Django 5.2.9 on 2025-12-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_department_role_alter_member_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='heads',
            field=models.ManyToManyField(blank=True, related_name='headed_departments', to='members.member'),
        ),
    ]
