# Generated by Django 5.2.9 on 2025-12-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_department_heads'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
